### Introduction to Python
#### Date: Sep 06,2023
#### Submission must be made through Github
You are required to complete all tasks correctly (or almost correctly) . You are free to use any material (lecture, Stackoverflow etc.) except full solutions but you should first try to figure them out on your own. We use an nbgrader for partially autograding the assignments. Please DO NOT delete or copy cells. You can add new cells but your solutions should go into the designated cells.

`range()` practice

1 . Print the numbers between 60 and 69 inclusive.

In [33]:
for number in range(60,70):
  print(number, end = ' ')
#raise NotImplementedError()

60 61 62 63 64 65 66 67 68 69 

2 . Read numbers until 0 and print their mean and standard deviation without using a list.

In [35]:
sum_of_squares = 0
total = 0
counter = 0
while(True):
  number = int(input('Enter a number:'))
  if number == 0:
    break

  sum_of_squares += (number**2)
  total = total + number
  counter = counter + 1

mean = total/ counter
print("Mean:" +str(mean))

std= ((sum_of_squares/counter)-mean**2)**(1/2)
print("standard Deviation: " + str(std))

#raise NotImplementedError()

Enter a number:1
Enter a number:2
Enter a number:3
Enter a number:4
Enter a number:5
Enter a number:0
Mean:3.0
standard Deviation: 1.4142135623730951


##### Lists
3 . Print the odd numbers from this list. `l = [2, 3, -2, -7, 0, 2, 3]`

In [36]:
l = [2, 3, -2, -7, 0, 2, 3]
for number in l:
  if number%2 == 0:
    continue
  else:
    print(number, end = ' ')
#raise NotImplementedError()

3 -7 3 

##### Functions
4 . Write a function that takes an integer parameter `(N)` and returns a list of the first `N` prime numbers starting from 2.

In [37]:
def is_prime(n):
  if n==0 or n==1:
    return False

  for i in range(2, n):
    if n%i==0:
      return False
  else:
      return True


def get_n_primes(N):
  primes = []
  num = 2
  while len(primes) < N:
    if is_prime(num)== True:
      primes.append(num)
    num+=1

  return primes
#raise NotImplementedError()

In [38]:
get_n_primes(3)

[2, 3, 5]

In [39]:
get_n_primes(0)

[]

In [40]:
assert(get_n_primes(3) == [2, 3, 5])
assert(get_n_primes(0) == [])

5. Write a function that takes an integer parameter (N) and returns the Nth Fibonacci number.

 The Fibonacci series is defined as:

$$
F_n = F_{n-1} + F_{n-2} \text{ for } n>1\\
F_0 = 0\\
F_1 = 1
$$

The first few elements of the Fibonacci series are 0, 1, 1, 2, 3, 5, 8, 13 etc.

Raise a `ValueError` if $N<0$.


In [41]:
def get_nth_fibonacci(n):
  if n < 0:
    raise ValueError('Enter positive number')
  elif n==0:
    return (0)
  elif n==1:
    return 1
  elif n ==2:
    return 1
  else:
    return get_nth_fibonacci(n-1)+ get_nth_fibonacci(n-2)


print(get_nth_fibonacci)

#raise NotImplementedError()

<function get_nth_fibonacci at 0x7a1b1b4a77f0>


In [42]:
get_nth_fibonacci(0)

0

In [43]:
assert(get_nth_fibonacci(0) == 0)
assert(get_nth_fibonacci(1) == 1)
assert(get_nth_fibonacci(2) == 1)
assert(get_nth_fibonacci(5) == 5)
assert(get_nth_fibonacci(7) == 13)

try:
    get_nth_fibonacci(-2)
except ValueError:
    pass
else:
    AssertionError("TEST FAILS. Negative index should raise a ValueError.")

6 . Create a function that take a list and a predicate (function with boolean return value) as parameters and returns a new list of those elements which the predicate return True. A predicate is a function that takes one element and return `True` or `False`, for example `is_even`, `is_prime`. If you implemented The following tests should run.


In [44]:
# YOUR CODE HERE
def is_even(N):
    return N % 2 == 0

def is_odd(N):
  return N % 2!= 0

def is_prime(N):
  if N==0 or N==1:
    return False

  for i in range(2, N):
    if N%i==0:
      return False
  else:
    return True


def filter_list(lst, predicate):
  return [N for N in lst if predicate(N)]


#raise NotImplementedError()

In [45]:
l1 = [1, 2, 3, 4, 19, 35, 11]
l2 = [1, 4, 9, 16, 25]
assert(filter_list(l1, is_odd) == [1, 3, 19, 35, 11])
assert(filter_list(l1, is_prime) == [2, 3, 19, 11])
assert(filter_list(l2, is_prime) == [])

7.  Reduce is a function that applies a two argument function against an accumulator and each element in the sequence (from left to right) to reduce it to a single value. If no initial value is provided, the accumulator is initialized with the return value of the function run on the first two elements of the sequence.

```
reduce([1, 2, 3], product) ---> 6
reduce([1, 2, 3], product, accumulator=10) ---> 60
reduce(["foo", "bar"], string_addition) ---> "foobar"
reduce(["foo", "bar"], string_addition, accumulator="hello") ---> "hellofoobar"
```

In [11]:
# YOUR CODE HERE
import numpy as np

def reduce(l1, func, acc=None):
  my_array = l1.copy()
  if acc != None:
    my_array.insert(0, acc)
    return func(my_array)
  else:
    return func(my_array)

def product(x):
  return np.product(x)

def add(x):
  return np.sum(x)

def string_len_add(x):
  length = 0
  for item in x:
    if isinstance(item, int):
      length += item
    else:
      length += len(item)
  return length

def count_of_odd_numbers(x):
  count= 0
  for i in x:
    if i%2!= 0:
      count += 1
  return count


def max_number(x):
  return np.amax(x)

def longest_string(x):
    longest = ''
    for s in x:
        if len(s) > len(longest):
            longest = s
    return longest



reduce([1, 2, 3], product)

#raise NotImplementedError()

6

In [12]:
l1 = [1, 2, -1, 5]
l2 = ["foo", "bar", "hello"]

assert(reduce(l1, add) == 7)
assert(reduce(l1, add, 10) == 17)
assert(reduce(l2, string_len_add, 0) == 11)

8. Use your reduce function for the following operations:

##### a. count the number of odd elements in a list of integers,
##### b. find the maximum of a list of integers,
##### c. find the longest string in list of strings.

``` Test your solutions. ```

In [14]:
# a
l4 = [3, 2, 11, 6, 19,]
reduce(l4, count_of_odd_numbers)

#raise NotImplementedError()

3

In [15]:
# b
l5 = [4, 20, 8, 3, 10]
reduce(l5, max_number)
#raise NotImplementedError()

20

In [16]:
# c
l6 = ["Monday", "Tuesday", "Wednesday", "sunday"]
reduce(l6, longest_string)
#raise NotImplementedError()

'Wednesday'

9. Create a function that takes a matrix of size NxM and returns the pairwise L2 distance of each row pair.

For input $A^{N \times M}$, the output should be $D^{N \times N}$ where: $D_{i,j} = L_2 (A_i, A_j)$

In [21]:
import numpy as np

def pairwise_row_distance(A):
    A = np.array(A, dtype=float)
    num_rows = A.shape[0]
    D = np.zeros((num_rows, num_rows), dtype=float)

    for i in range(num_rows):
        for j in range(num_rows):
            D[i][j] = np.sqrt(np.sum((A[i] - A[j]) ** 2))
    return D


In [24]:
D = pairwise_row_distance([[1, 0, 2], [0, 2, 1]])
# should be a matrix
#assert is_matrix(D) == True
assert len(D) == 2
assert len(D[0]) == 2
assert D[0][0] == 0
assert abs(D[0][1] - 2.449489742783178) < 1e-3
assert abs(D[1][0] - 2.449489742783178) < 1e-3
assert D[1][1] == 0

# should be symmetric
#assert transpose(D) == D

10 . Object Oriented Programming
 Define a class named `A` with a 'constructor' that takes a single parameter and stores it in an attribute named `value`. Add a `print_value` method to the class. Instantiate the class and call the `print_value` method.

In [46]:
class A():
  def __init__ (self, value):
    self.value = value

  def print_value(self):
      print(f'{self.value} ')

#raise NotImplementedError()

In [47]:
a = A("abc")
a.print_value()

abc 


11.  Define a class named `B`, whose `__init__` takes two parameters and stores one in a public attribute and the other in a private attribute named `this_is_public` and `__this_is_private` respectively. Check the class's ``__dict__``  attribute and find out the mangled name of the private attribute.

In [48]:
# YOUR CODE HERE
class B:
    def __init__(self, parameter1, parameter2):
        self.this_is_public = parameter1
        self.__this_is_private = parameter2


print(B.__dict__)
#raise NotImplementedError()

{'__module__': '__main__', '__init__': <function B.__init__ at 0x7a1b1b4a5bd0>, '__dict__': <attribute '__dict__' of 'B' objects>, '__weakref__': <attribute '__weakref__' of 'B' objects>, '__doc__': None}


In [51]:
b.this_is_public

1

In [49]:
b = B(1, 2)
assert b.this_is_public == 1
try:
    b.__this_is_private
    print("This should not happen.")
except AttributeError:
    print("Failed to access private attribute, this is good :)")

Failed to access private attribute, this is good :)


13 . Inheritance

###### Guess the output without running the cell.

In [50]:
class A(object): pass
class B(A): pass
class C(A): pass
class D(B): pass

a = A()
b = B()
c = C()
d = D()

print(isinstance(a, object))
print(isinstance(b, object))
print(isinstance(a, B))
print(isinstance(b, A))
print(isinstance(d, A))

True
True
False
True
True


In [51]:
print(issubclass(C, object))
print(issubclass(D, B))
print(issubclass(B, D))
print(issubclass(B, B))

True
True
False
True


#### Create a Cat, a Dog, a Fish and a Eagle class.

The animals have the following attributes:

1. cats, dogs and eagles can make a sound (this should be a make_sound function that prints the animals sound),
2. all animals have an age and a number_of_legs attribute,
3. cats and dogs have a fur_color attribute. They can be instantiated with a single color or a list or tuple of colors.

Use inheritance and avoid repeating code. Use default values in the constructors.

In [30]:
class Animal:
    def __init__(self,name,age=2,number_of_legs=4):
        self.age = age
        self.number_of_legs = number_of_legs
        self.name = name

class Eagle(Animal):
    def __init__(self,name,age=1,number_of_legs=2,sound="mwoo"):
        self.sound = sound
        super().__init__(name,age,number_of_legs)

    def make_sound(self):
        print(self.sound)

class Cat(Eagle):
    def __init__(self,name,fur=None,age=3,number_of_legs=4,sound="mweo"):
        self.fur = fur
        super().__init__(name,age,number_of_legs,sound)

class Dog(Cat):
    pass

class Fish(Animal):
    pass


In [31]:
try:
    cat = Cat("Fluffy", age=3, fur="white")
    dog = Dog("Cherry", age=1, fur=("white", "brown", "black"))
    fish = Fish("King")
    eagle = Eagle("Bruce", age=2)
    animals = [cat, dog, fish, eagle]
except Exception as e:
    print(f'Could not initialize an animal: {e}')

#### Numpy basic exercises

Use vectorization and avoid for loops in all exercises. Implement each exercise as a single function.

##### Implement standardization for 2D arrays.

Standardization is defined as:

\begin{equation*}
X_{std} = \frac{X - \mu}{\sigma},
\end{equation*}

where $\mu$ is the mean of each row and $\rho$ is the standard deviation of each column.

In [32]:
import numpy as np

def standardize(matrix):
    mean = np.mean(matrix, axis=1)
    standard_deviation = np.std(matrix, axis=0)
    standard_matrix = (matrix - mean[:, np.newaxis]) / standard_deviation
    return standard_matrix

X_std = standardize(np.array([[1, 2], [2, 3], [1, 2]]))
X_std

array([[-1.06066017,  1.06066017],
       [-1.06066017,  1.06066017],
       [-1.06066017,  1.06066017]])

#### Implement normalization for 2D arrays.

Normalization is defined as:

\begin{equation*}
X_{norm} = \frac{X - X_{min}}{X_{max} - X_{min}}
\end{equation*}

In [26]:
import numpy as np
def normalize(X):

  X_min = np.min(X, axis =0)
  X_max = np.max(X, axis =0)
  X_normalized = (X-X_min)/(X_max-X_min)
  return (X_normalized)


#raise NotImplementedError()

X = np.arange(6).reshape(2, 3)
X[1, 2] = -5
print(X)
normalize(X)

[[ 0  1  2]
 [ 3  4 -5]]


array([[0., 0., 1.],
       [1., 1., 0.]])

In [27]:
answer = np.array(
    [[0., 0., 1.],
     [1., 1., 0.]]
)
X_norm = normalize(X)
assert np.allclose(X_norm, answer)
